# Generated by Django 5.2.1 on 2025-10-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universalcontent',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='universalcontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='universalcontent',
            name='full_content',
            field=models.TextField(blank=True, help_text='For pages only'),
        ),
        migrations.AddField(
            model_name='universalcontent',
            name='link',
            field=models.CharField(blank=True, help_text='Redirect link', max_length=500),
        ),
        migrations.AlterField(
            model_name='universalcontent',
            name='content_type',
            field=models.CharField(choices=[('section', 'Main Section (Home/Career/etc)'), ('card', 'Card'), ('folder', 'Folder/Category'), ('page', 'Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='universalcontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL'),
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='color',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='login_required',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='redirect_link',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='section',
        ),
        migrations.RemoveField(
            model_name='universalcontent',
            name='slug',
        ),
    ]
