# Generated by Django 5.2.1 on 2025-10-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_universalcontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionAbroadSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='admission_abroad_sub/')),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('icon_color', models.CharField(choices=[('#f39c12', 'Orange'), ('#e74c3c', 'Red'), ('#2ecc71', 'Green'), ('#3498db', 'Blue'), ('#9b59b6', 'Purple')], default='#f39c12', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='main_app.admissionabroadcard')),
                ('parent_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_app.admissionabroadsubcategory')),
            ],
            options={
                'verbose_name': 'Admission Abroad Sub Category',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionAbroadPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Full page content (HTML supported)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='admission_abroad_pages/')),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='main_app.admissionabroadsubcategory')),
            ],
            options={
                'ordering': ['sub_category', 'order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UniversalContent',
        ),
    ]
