# Generated by Django 5.2.1 on 2025-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_admissionabroadcard_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distanceeducationcard',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Distance Education Card', 'verbose_name_plural': 'Distance Education Cards'},
        ),
        migrations.AddField(
            model_name='distanceeducationcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='distanceeducationcard',
            name='border_color',
            field=models.CharField(default='#3498db', max_length=20),
        ),
        migrations.AlterField(
            model_name='distanceeducationcard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='distanceeducationcard',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distanceeducationcard',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
