# Generated by Django 5.2.1 on 2025-10-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_onlineeducationcard_slug_onlineeducationsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='course',
            field=models.CharField(blank=True, help_text='Select course (leave blank for all courses)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Select state (leave blank for all states)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='main_app.state'),
        ),
    ]
