# Generated by Django 5.2.1 on 2025-10-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_subcategory_course_subcategory_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionabroadsubcategory',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Admission Abroad Sub Category', 'verbose_name_plural': 'Admission Abroad Sub Categories'},
        ),
        migrations.AddField(
            model_name='admissionabroadsubcategory',
            name='course',
            field=models.CharField(blank=True, help_text='Select course (leave blank for all courses)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionabroadsubcategory',
            name='student_state',
            field=models.ForeignKey(blank=True, help_text="Student's home state (leave blank for all states)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_abroad_sub_categories', to='main_app.state'),
        ),
        migrations.AddField(
            model_name='admissionabroadsubcategory',
            name='target_country',
            field=models.ForeignKey(blank=True, help_text='Target country (e.g., Russia, USA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_abroad_subcategories', to='main_app.country'),
        ),
    ]
