# Generated by Django 5.2.1 on 2025-10-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_distanceeducationsubcategory_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineeducationsubcategory',
            name='course',
            field=models.CharField(blank=True, help_text='Select course (leave blank for all courses)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlineeducationsubcategory',
            name='student_state',
            field=models.ForeignKey(blank=True, help_text="Student's home state (leave blank for all states)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_education_sub_categories', to='main_app.state'),
        ),
        migrations.AddField(
            model_name='onlineeducationsubcategory',
            name='target_country',
            field=models.ForeignKey(blank=True, help_text='Target country (for international programs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_education_subcategories', to='main_app.country'),
        ),
    ]
