# Generated by Django 5.2.1 on 2025-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_onlineeducationsubcategory_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
