# Generated by Django 5.2.1 on 2025-10-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_userregistration_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionindiacard',
            name='card_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', help_text='Free ya Paid?', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionindiacard',
            name='description',
            field=models.TextField(blank=True, help_text='Card ke baare mein description'),
        ),
        migrations.AddField(
            model_name='admissionindiacard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price (agar paid hai to yaha likho)', max_digits=10),
        ),
        migrations.CreateModel(
            name='StudentCardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(blank=True, help_text='Credit Card, UPI, etc.', max_length=50)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='main_app.admissionindiacard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_purchases', to='main_app.userregistration')),
            ],
            options={
                'verbose_name': 'Student Card Purchase',
                'verbose_name_plural': 'Student Card Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('student', 'card')},
            },
        ),
    ]
