# Generated by Django 5.2.1 on 2025-10-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_admissionindiacard_card_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementQuotaCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_seats_available', models.IntegerField(default=0, help_text='Number of management quota seats')),
                ('courses_offered', models.TextField(help_text='Comma-separated list of courses available')),
                ('fee_structure', models.TextField(blank=True, help_text='Fee details for management quota')),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_applications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_quota', to='main_app.college')),
            ],
            options={
                'verbose_name': 'Management Quota College',
                'verbose_name_plural': 'Management Quota Colleges',
            },
        ),
        migrations.CreateModel(
            name='ManagementQuotaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('tenth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entrance_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenth_marksheet', models.FileField(upload_to='management_quota/tenth/')),
                ('twelfth_marksheet', models.FileField(upload_to='management_quota/twelfth/')),
                ('exam_scorecard', models.FileField(blank=True, null=True, upload_to='management_quota/exam/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], default='pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mq_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_quota_applications', to='main_app.userregistration')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.managementquotacollege')),
            ],
            options={
                'verbose_name': 'Management Quota Application',
                'verbose_name_plural': 'Management Quota Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'college')},
            },
        ),
        migrations.CreateModel(
            name='ManagementQuotaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('submitted', 'Application Submitted'), ('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('waitlist', 'Added to Waitlist'), ('document_required', 'Additional Documents Required')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main_app.managementquotaapplication')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mq_notifications', to='main_app.userregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementQuotaSeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_roll_number', models.CharField(max_length=50, unique=True)),
                ('seat_number', models.CharField(max_length=50)),
                ('allotment_date', models.DateField()),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('allotted', 'Seat Allotted'), ('joined', 'Student Joined'), ('not_joined', 'Student Did Not Join')], default='allotted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocation', to='main_app.managementquotaapplication')),
            ],
            options={
                'verbose_name': 'Management Quota Seat Allocation',
                'verbose_name_plural': 'Management Quota Seat Allocations',
            },
        ),
    ]
