# Generated by Django 5.2.1 on 2025-10-25 09:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_managementquotacollege_managementquotaapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
