# Generated by Django 5.2.1 on 2025-10-25 11:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_contentpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionabroadpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
