# Generated by Django 5.2.1 on 2025-10-25 11:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_admissionabroadpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceeducationpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='distanceeducationpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='onlineeducationpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='onlineeducationpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
