# Generated by Django 5.2.1 on 2025-10-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_admissionabroadpage_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pages', to='main_app.country'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pages', to='main_app.state'),
        ),
    ]
